# Generated by Django 3.1.4 on 2020-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneid', models.TextField(blank=True, db_column='GeneID', null=True)),
                ('treated', models.FloatField(blank=True, null=True)),
                ('control', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exp',
                'managed': False,
            },
        ),
    ]
